/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import util.DatabaseThread;
import util.User;

/**
 *
 * @author austi
 */
public class BudgetScreen extends javax.swing.JFrame {

    /**
     * Creates new form budgetGUI
     */
    Color defaultColor;
    Color clickedColor;
    DatabaseThread databaseThread;
    User currentUser;

    public BudgetScreen() {
        
        initComponents();
        defaultColor = new Color(200, 240, 150);
        clickedColor = new Color(255, 255, 204);
        
        budgetButton.setBackground(defaultColor);
        progressButton.setBackground(defaultColor);

        setVisible(true);
    }

    public BudgetScreen(DatabaseThread databaseThread) {
        
        this.databaseThread = databaseThread;
        currentUser = databaseThread.getCurrentUser();
        initComponents();
        defaultColor = new Color(200, 240, 150);
        clickedColor = new Color(255, 255, 204);
        
        budgetButton.setBackground(defaultColor);
        progressButton.setBackground(defaultColor);

        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        javax.swing.JPanel jPanel3;
        javax.swing.JPanel jPanel1;
        javax.swing.JLabel jLabel8;
        javax.swing.JLabel jLabel4;
        javax.swing.JLabel jLabel1;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        budgetButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        progressButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewScreen = new javax.swing.JDesktopPane();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        String fontName = "Tahoma";
        jLabel1.setFont(new java.awt.Font(fontName, 0, 36)); // NOI18N
        jLabel1.setText("Set Your Budget");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE));

        jPanel3.setBackground(new java.awt.Color(200, 240, 150));

        budgetButton.setBackground(new java.awt.Color(200, 240, 150));
        budgetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickActionPerformed(evt);
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font(fontName, 0, 18)); // NOI18N
        jLabel4.setText("Set Budget");

        javax.swing.GroupLayout budgetButtonLayout = new javax.swing.GroupLayout(budgetButton);
        budgetButton.setLayout(budgetButtonLayout);
        budgetButtonLayout.setHorizontalGroup(
                budgetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(budgetButtonLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4)
                                .addContainerGap(50, Short.MAX_VALUE)));
        budgetButtonLayout.setVerticalGroup(
                budgetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, budgetButtonLayout.createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addContainerGap()));

        progressButton.setBackground(new java.awt.Color(200, 240, 150));
        progressButton.setPreferredSize(new java.awt.Dimension(192, 57));
        progressButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickActionPerformed(evt);
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font(fontName, 0, 18)); // NOI18N
        jLabel8.setText("Progress Check");

        javax.swing.GroupLayout progressButtonLayout = new javax.swing.GroupLayout(progressButton);
        progressButton.setLayout(progressButtonLayout);
        progressButtonLayout.setHorizontalGroup(
                progressButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                progressButtonLayout.createSequentialGroup()
                                        .addContainerGap(31, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(41, 41, 41)));
        progressButtonLayout.setVerticalGroup(
                progressButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                progressButtonLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addContainerGap()));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(budgetButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(progressButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(280, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(budgetButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(progressButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        viewScreen.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout viewScreenLayout = new javax.swing.GroupLayout(viewScreen);
        viewScreen.setLayout(viewScreenLayout);
        viewScreenLayout.setHorizontalGroup(
                viewScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        viewScreenLayout.setVerticalGroup(
                viewScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 541, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(viewScreen));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewScreen, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }

    private void clickActionPerformed(MouseEvent evt) {
        if (evt.getSource() == progressButton) {
            progressButtonMouseClicked();
        }
        if (evt.getSource() == budgetButton) {
            budgetButtonMouseClicked();
        }
    }

    private void pressActionPerformed(MouseEvent evt) {
        if (evt.getSource() == budgetButton) {
            budgetButtonMousePressed();
        }
        if (evt.getSource() == progressButton) {
            progressButtonMousePressed();
        }
    }

    private void budgetButtonMousePressed() {
        budgetButton.setBackground(clickedColor);
        progressButton.setBackground(defaultColor);
    }

    private void progressButtonMousePressed() {
        progressButton.setBackground(clickedColor);
        budgetButton.setBackground(defaultColor);
    }

    private void budgetButtonMouseClicked() {
        var budget = databaseThread.getUserBudgets();

        int option = JOptionPane.showOptionDialog(this, "Select a budget", "budget Selection", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, budget.toArray(), null);

        if (option == -1) {
            return;
        }
        if (option != -1) {
            viewScreen.removeAll();
            SetBudgetInternalFrame budgetInternalFrame = new SetBudgetInternalFrame(budget.get(option), databaseThread);
            viewScreen.add(budgetInternalFrame);
            viewScreen.revalidate();
            viewScreen.repaint();
            budgetInternalFrame.setVisible(true);
        }
    }

    private void progressButtonMouseClicked() {
        ProgressInternalFrame progress = new ProgressInternalFrame(this.databaseThread);
        viewScreen.removeAll();
        viewScreen.add(progress).setVisible(true);
    }// GEN-LAST:event_progressButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane viewScreen;
    private javax.swing.JPanel budgetButton;
    private javax.swing.JPanel progressButton;
    // End of variables declaration//GEN-END:variables

}
