/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.SwingUtilities;

import util.DatabaseThread;
import util.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author manuella
 */
public class HomeScreen extends javax.swing.JFrame {
    User currentUser;
    DatabaseThread databaseThread;
   
    public HomeScreen() {
        initComponents();
        setVisible(true);
    }

    public HomeScreen(DatabaseThread databaseThread, User currentUser) {
        this.currentUser = currentUser;
        this.databaseThread = databaseThread;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        java.awt.Button transaction;
        java.awt.Button signout;
        java.awt.Button makeBudget;
        java.awt.Label label3;
        java.awt.Label label2;
        java.awt.Label label1;
        javax.swing.JPanel jPanel2;
        javax.swing.JPanel jPanel1;
        java.awt.Button contact;
        java.awt.Button AccBalance;
        java.awt.Button SetGoals;
        java.awt.Button GenerateReport;
        java.awt.Button viewTransaction;
        java.awt.Button EditProfile;
        java.awt.Button ViewGoals;
        java.awt.Button viewBudget;
        java.awt.Button viewReports;
        java.awt.Button updateBudget;
        final String DIALOG = "Dialog";

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        viewBudget = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        makeBudget = new java.awt.Button();
        updateBudget = new java.awt.Button();
        signout = new java.awt.Button();
        label3 = new java.awt.Label();
        contact = new java.awt.Button();
        EditProfile = new java.awt.Button();
        viewReports = new java.awt.Button();
        viewTransaction = new java.awt.Button();
        GenerateReport = new java.awt.Button();
        SetGoals = new java.awt.Button();
        transaction = new java.awt.Button();
        ViewGoals = new java.awt.Button();
        AccBalance = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        viewBudget.setBackground(new java.awt.Color(153, 0, 0));
        viewBudget.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        viewBudget.setForeground(new java.awt.Color(255, 204, 204));
        viewBudget.setLabel("View budget\n");

        label1.setFont(new java.awt.Font(DIALOG, 3, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 204, 204));
        label1.setText("HOME");

        label2.setFont(new java.awt.Font(DIALOG, 3, 48)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 204, 204));
        label2.setText("SCREEN");

        makeBudget.setBackground(new java.awt.Color(153, 0, 0));
        makeBudget.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        makeBudget.setForeground(new java.awt.Color(255, 204, 204));
        makeBudget.setLabel("Make Budget");

        updateBudget.setBackground(new java.awt.Color(153, 0, 0));
        updateBudget.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        updateBudget.setForeground(new java.awt.Color(255, 204, 204));
        updateBudget.setLabel("Update Budget");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(viewBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(makeBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(updateBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signout.setBackground(new java.awt.Color(153, 0, 0));
        signout.setFont(new java.awt.Font(DIALOG, 3, 36)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 204, 204));
        signout.setLabel("Sign out\n");
        signout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Dispose of the current home screen
                dispose();
            }
        }

        label3.setFont(new java.awt.Font(DIALOG, 3, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(153, 0, 0));
        label3.setText("WELCOME TO YOUR PERSONAL FINANCE TRACKER");

        contact.setBackground(new java.awt.Color(153, 0, 0));
        contact.setFont(new java.awt.Font(DIALOG, 3, 36)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 204, 204));
        contact.setLabel("Help/Support");
        contact.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // When the button is clicked, create the BudgetGUI instance and show it
                Support budgetGUI = new Support();
                
                budgetGUI.setVisible(true);

                // Dispose of the current home screen
                dispose();
            }
        }

        EditProfile.setBackground(new java.awt.Color(153, 0, 0));
        EditProfile.setFont(new java.awt.Font(DIALOG, 3, 36)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(255, 204, 204));
        EditProfile.setLabel("Edit Profile");
        EditProfile.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Profile budgetGUI = new Profile();
                
                budgetGUI.setVisible(true);
                // Dispose of the current home screen
                dispose();
            }
        }

        viewReports.setBackground(new java.awt.Color(255, 204, 204));
        viewReports.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        viewReports.setForeground(new java.awt.Color(153, 0, 0));
        viewReports.setLabel("View Reports");

        viewTransaction.setBackground(new java.awt.Color(255, 204, 204));
        viewTransaction.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        viewTransaction.setForeground(new java.awt.Color(153, 0, 0));
        viewTransaction.setLabel("View Transactions");
        viewTransaction.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // When the button is clicked, create the BudgetGUI instance and show it
                ViewATransactionScreen budgetGUI = new ViewATransactionScreen();
                
                budgetGUI.setVisible(true);

                // Dispose of the current home screen
                dispose();
            }
        }
        GenerateReport.setBackground(new java.awt.Color(255, 204, 204));
        GenerateReport.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        GenerateReport.setForeground(new java.awt.Color(153, 0, 0));
        GenerateReport.setLabel("Generate Report");
         GenerateReport.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                Object[] options = {"expenses", "income", "exit"};

        // Show the option dialog with a question icon
        int selectedOption = JOptionPane.showOptionDialog(null,
                "What Report would you like? :", "Question",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);

        if (selectedOption == JOptionPane.CLOSED_OPTION) {
            // User closed the dialog, exit the program
            System.exit(0);
        }

        // Do something based on the selected option
        switch (selectedOption) {
            case 0:
                System.out.println("Generate expense report");
                break;
            case 1:
                System.out.println("Generate income report");
                break;
            case 2:
                System.out.println("leaving");
              
                break;
            default:
                System.out.println("Invalid selection");
        }
    
      
                
            }
        }


        SetGoals.setBackground(new java.awt.Color(255, 204, 204));
        SetGoals.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        SetGoals.setForeground(new java.awt.Color(153, 0, 0));
        SetGoals.setLabel("Set Goals");

        transaction.setActionCommand("Add Transaction");
        transaction.setBackground(new java.awt.Color(255, 204, 204));
        transaction.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        transaction.setForeground(new java.awt.Color(153, 0, 0));
        transaction.setLabel("Add Transaction");
        transaction.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // When the button is clicked, create the BudgetGUI instance and show it
                InputTransaction budgetGUI = new InputTransaction();
                
                budgetGUI.setVisible(true);

                // Dispose of the current home screen
                dispose();
            }
        }

        ViewGoals.setBackground(new java.awt.Color(255, 204, 204));
        ViewGoals.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        ViewGoals.setForeground(new java.awt.Color(153, 0, 0));
        ViewGoals.setLabel("View Goals");

        AccBalance.setBackground(new java.awt.Color(255, 204, 204));
        AccBalance.setFont(new java.awt.Font(DIALOG, 3, 24)); // NOI18N
        AccBalance.setForeground(new java.awt.Color(153, 0, 0));
        AccBalance.setLabel("View account balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addGap(101, 101, 101))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(viewTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(72, 72, 72)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(viewReports, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ViewGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SetGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(60, 60, 60))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(AccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(viewReports, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(AccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) { 
        databaseThread.setLoggedIn(false);  
        databaseThread.interrupt();
        SwingUtilities.invokeLater(() -> new Login(databaseThread));
        this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }   
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreen().setVisible(true));
    }                
}
