/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import util.Budget;
import util.Category;
import util.DatabaseThread;
import util.User;

/**
 *
 * @author austi
 */
public class SetBudgetInternalFrame extends javax.swing.JInternalFrame {
    User currentUser;
    DatabaseThread databaseThread;
    Budget selectedBudget;
    List<Category> categories = Category.getCategoryFromDb();

    /**
     * Creates new form setBudgetGUI
     */
    public SetBudgetInternalFrame() {
        initComponents();
    }

    public SetBudgetInternalFrame(Budget selectedBudget, DatabaseThread databaseThread) {
        this.selectedBudget = selectedBudget;
        this.databaseThread = databaseThread;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        javax.swing.JLabel jLabel2;
        javax.swing.JLabel jLabel1;
        javax.swing.JButton jButton2;
        javax.swing.JButton jButton1;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        categoryField1 = new javax.swing.JTextField();
        amountField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        categoryComboBox = new JComboBox<>();
        for (Category ct : categories) {
            categoryComboBox.addItem(ct.getName());
        }

        setBackground(new java.awt.Color(255, 255, 204));

        String fontName = "Tahoma";
        jLabel1.setFont(new java.awt.Font(fontName, 0, 18)); // NOI18N
        jLabel1.setText("Category: ");

        jLabel2.setFont(new java.awt.Font(fontName, 0, 18)); // NOI18N
        jLabel2.setText("Amount:");

        jButton1.setFont(new java.awt.Font(fontName, 0, 18)); // NOI18N
        jButton1.setText("Set");

        jButton2.setFont(new java.awt.Font(fontName, 0, 18)); // NOI18N
        jButton2.setText("Reset");

        jButton2.addActionListener(this::jButton2MouseClicked);
        jButton1.addActionListener(this::jButton1MouseClicked);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 117,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(categoryComboBox)
                                                        .addComponent(amountField2,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 163,
                                                                Short.MAX_VALUE))
                                                .addGap(33, 33, 33)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53,
                                                Short.MAX_VALUE)
                                        .addComponent(amountField2))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(109, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(ActionEvent e) {
        categoryField1.setText(" ");
        amountField2.setText(" ");
    }

    private void jButton1MouseClicked(ActionEvent e) {
        int budgetAmount = Integer.parseInt(amountField2.getText());
        Category category = Category.searchForCategory(categories, ((String) categoryComboBox.getSelectedItem()));
        Budget newBudget = new Budget(selectedBudget.getBudgetName(), selectedBudget.getStartDate(), selectedBudget.getEndDate());
        newBudget.allocateCategoryBudget(category, budgetAmount);
        databaseThread.updateUserBudget(newBudget);
        var success = "Category " + category.getName() + "Updated Successfully for " + budgetAmount;
        JOptionPane.showMessageDialog(SetBudgetInternalFrame.this, success, "Success", JOptionPane.INFORMATION_MESSAGE);
        newBudget.generateBudgetReport();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField2;
    private javax.swing.JTextField categoryField1;
    private JComboBox<String> categoryComboBox;
    // End of variables declaration//GEN-END:variables
}
